export const EventNames = {
  entryCreated: 'entry.created',
  batchEntriesCreated: 'entries.batch.created',
} as const;

export const BusinessContextKeys = {
  controllerOperation: 'controllerOperation',
  eventHandler: 'eventHandler',

  userId: 'userId',
  entryId: 'entryId',
  lawnSegmentId: 'lawnSegmentId',
  customerId: 'customerId',
  subscriptionId: 'subscriptionId',
  sessionId: 'sessionId',
  priceId: 'priceId',

  analyticsYear: 'analyticsYear',

  entriesReturned: 'entriesReturned',
  entryCreated: 'entryCreated',
  entryDeleted: 'entryDeleted',
  batchSize: 'batchSize',
  batchCreated: 'batchCreated',
  batchFailed: 'batchFailed',
  searchResultsCount: 'searchResultsCount',
  productsCount: 'productsCount',
  hasProductImages: 'hasProductImages',

  lawnSegmentsCount: 'lawnSegmentsCount',
  lawnSegmentCreated: 'lawnSegmentCreated',
  lawnSegmentUpdated: 'lawnSegmentUpdated',
  lawnSegmentDeleted: 'lawnSegmentDeleted',

  subscriptionTier: 'subscriptionTier',
  subscriptionStatus: 'subscriptionStatus',
  subscriptionFetchError: 'subscriptionFetchError',
  subscriptionCreated: 'subscriptionCreated',
  subscriptionUpdated: 'subscriptionUpdated',
  subscriptionUpdateError: 'subscriptionUpdateError',
  subscriptionDeleted: 'subscriptionDeleted',
  subscriptionCanceling: 'subscriptionCanceling',
  subscriptionDaysActive: 'subscriptionDaysActive',
  subscriptionCacheHit: 'subscriptionCacheHit',
  subscriptionDowngradedToFree: 'subscriptionDowngradedToFree',
  lifetimeSubscriptionAgeDays: 'lifetimeSubscriptionAgeDays',
  cancelAtPeriodEnd: 'cancelAtPeriodEnd',
  isPro: 'isPro',
  previousTier: 'previousTier',
  previousStatus: 'previousStatus',
  newTier: 'newTier',
  newStatus: 'newStatus',
  existingTier: 'existingTier',
  existingCustomerId: 'existingCustomerId',

  stripeOperation: 'stripeOperation',
  stripeErrorType: 'stripeErrorType',
  stripeErrorCode: 'stripeErrorCode',
  stripeErrorMessage: 'stripeErrorMessage',
  stripeStatus: 'stripeStatus',
  stripeSubscriptionId: 'stripeSubscriptionId',
  stripePriceId: 'stripePriceId',
  stripeCustomerId: 'stripeCustomerId',
  stripeCustomerDeleted: 'stripeCustomerDeleted',
  stripeCustomerMissing: 'stripeCustomerMissing',
  stripeCustomerCreated: 'stripeCustomerCreated',
  customerEmail: 'customerEmail',
  customerName: 'customerName',
  customerLookupError: 'customerLookupError',
  customerErrorCode: 'customerErrorCode',
  customerCreationError: 'customerCreationError',
  creatingNewCustomer: 'creatingNewCustomer',
  newCustomerId: 'newCustomerId',

  checkoutOperation: 'checkoutOperation',
  checkoutTier: 'checkoutTier',
  checkoutUserId: 'checkoutUserId',
  checkoutUserEmail: 'checkoutUserEmail',
  checkoutSessionCreated: 'checkoutSessionCreated',
  checkoutMissingUrl: 'checkoutMissingUrl',
  checkoutCreationError: 'checkoutCreationError',

  portalOperation: 'portalOperation',
  portalUserId: 'portalUserId',
  portalSessionFailed: 'portalSessionFailed',
  portalSessionCreated: 'portalSessionCreated',
  portalMissingUrl: 'portalMissingUrl',
  portalCreationError: 'portalCreationError',

  webhookOperation: 'webhookOperation',
  webhookError: 'webhookError',
  webhookUserId: 'webhookUserId',
  webhookVerificationFailed: 'webhookVerificationFailed',

  cacheGetError: 'cacheGetError',
  cacheSetError: 'cacheSetError',
  cacheDelError: 'cacheDelError',
  cacheUserId: 'cacheUserId',
  cacheTier: 'cacheTier',

  emailOperation: 'emailOperation',
  emailError: 'emailError',
  emailSent: 'emailSent',
  emailMessageId: 'emailMessageId',
  emailErrorCode: 'emailErrorCode',
  emailErrorResponse: 'emailErrorResponse',
  fromEmail: 'fromEmail',
  senderEmail: 'senderEmail',
  feedbackType: 'feedbackType',

  fileSize: 'fileSize',
  fileMimeType: 'fileMimeType',
  s3UploadSuccess: 's3UploadSuccess',
  batchUploadCount: 'batchUploadCount',
  batchUploadSuccess: 'batchUploadSuccess',

  usageIncrementError: 'usageIncrementError',
  usageIncremented: 'usageIncremented',
  usageIncrementBatchError: 'usageIncrementBatchError',
  usageBatchIncremented: 'usageBatchIncremented',
  usageOperation: 'usageOperation',
  count: 'count',
  feature: 'feature',
  featureCheck: 'featureCheck',
  featureName: 'featureName',
  featureAccessError: 'featureAccessError',
  entryUsage: 'entryUsage',
  entryLimit: 'entryLimit',
  newUsageCount: 'newUsageCount',

  priceIdMissing: 'priceIdMissing',
  requestedTier: 'requestedTier',
  invalidTier: 'invalidTier',
  reason: 'reason',
  pricingCacheHit: 'pricingCacheHit',
  pricingFetched: 'pricingFetched',
  pricingFetchError: 'pricingFetchError',

  activitiesCount: 'activitiesCount',

  settingsFound: 'settingsFound',
  settingsUpdated: 'settingsUpdated',
  settingsCreated: 'settingsCreated',

  gddDormancyReset: 'gddDormancyReset',
  gddCycleStatus: 'gddCycleStatus',
  gddTarget: 'gddTarget',
  gddDaysSinceLastApp: 'gddDaysSinceLastApp',

  productId: 'productId',
  productsReturned: 'productsReturned',
  productCreated: 'productCreated',
  productHidden: 'productHidden',
  productUnhidden: 'productUnhidden',

  stripeEventId: 'stripeEventId',
  stripeEventType: 'stripeEventType',
  stripeCreated: 'stripeCreated',
  webhookEventSaved: 'webhookEventSaved',
  webhookDuplicate: 'webhookDuplicate',
  duplicateEventId: 'duplicateEventId',
  webhookSaveError: 'webhookSaveError',
  errorCode: 'errorCode',
  webhookProcessingComplete: 'webhookProcessingComplete',
  webhookProcessingFailed: 'webhookProcessingFailed',
  processingError: 'processingError',
  errorStack: 'errorStack',
  processingEventType: 'processingEventType',
  unhandledEventType: 'unhandledEventType',
  unhandledEvent: 'unhandledEvent',
  webhookProcessed: 'webhookProcessed',
  checkoutHandler: 'checkoutHandler',
  sessionMode: 'sessionMode',
  checkoutSkipped: 'checkoutSkipped',
  sessionStatus: 'sessionStatus',
  checkoutCompleted: 'checkoutCompleted',
  verificationError: 'verificationError',

  fileUrl: 'fileUrl',
  downloadError: 'downloadError',

  startDate: 'startDate',
  endDate: 'endDate',
  date: 'date',
  entryImageId: 'entryImageId',

  aiQueryType: 'aiQueryType',
  aiModel: 'aiModel',
  aiProvider: 'aiProvider',
  aiStreaming: 'aiStreaming',
  ragEntriesFound: 'ragEntriesFound',
  embeddingsProcessed: 'embeddingsProcessed',
  embeddingsErrors: 'embeddingsErrors',
  streamError: 'streamError',

  equipmentCount: 'equipmentCount',
  equipmentCreated: 'equipmentCreated',
  equipmentId: 'equipmentId',
  equipmentDeleted: 'equipmentDeleted',
  isActive: 'isActive',
  maintenanceId: 'maintenanceId',
  maintenanceRecordCreated: 'maintenanceRecordCreated',

  profilePictureUpdate: 'profilePictureUpdate',

  forecastLat: 'forecastLat',
  forecastLong: 'forecastLong',
} as const;
