name: Deploy to Railway Production

on:
  push:
    branches: [main, master]
    paths: ['backend/**']
  pull_request:
    types: [closed]
    branches: [main, master]
    paths: ['backend/**']

env:
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

jobs:
  deploy-production:
    # Only run if PR was merged (not just closed) OR if direct push to main
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH
      
      - name: Create railway.json for project linking
        run: |
          echo '{"projectId": "${{ secrets.RAILWAY_PROJECT_ID }}"}' > railway.json
      
      - name: Deploy to production environment
        working-directory: ./backend
        run: |
          # Deploy to the yardvark-backend service in production environment
          railway up --detach --environment production --service yardvark-backend
      
      - name: Create deployment notification
        uses: actions/github-script@v7
        with:
          script: |
            // Create a commit status or deployment notification
            const deploymentMessage = github.event_name === 'push' 
              ? `🚀 **Backend deployed to production!** (Direct push to ${github.ref_name})`
              : `🚀 **Backend deployed to production!** (PR #${{ github.event.pull_request.number }} merged)`;
            
            // If this was a PR merge, comment on the PR
            if (github.event.pull_request) {
              await github.rest.issues.createComment({
                issue_number: github.event.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `${deploymentMessage}
                
                **Production URL:** \`https://yardvark-backend-production.up.railway.app\`
                
                Your changes are now live in production! 🎉`
              });
            }
            
            console.log(deploymentMessage);